"""
rbxlx_builder.py

Constructs a Roblox .rbxlx (XML place file) from plain Python data:
- parts: geometry generated by the AI for "build" tasks
- scripts: Lua source generated by the AI for "script" tasks

The resulting XML can be uploaded directly via Roblox's Open Cloud
"Publish a place" endpoint (see roblox_publisher.py).

NOTE: The Roblox XML place format has many optional properties. This
builder targets the minimum needed for parts and scripts to appear and
work correctly. If Roblox changes their format or rejects a file,
open it in Studio manually once to compare against a file Studio saves,
and adjust the templates below accordingly.
"""

import itertools
import re
import xml.sax.saxutils as sx

# Characters not valid in XML 1.0 (most control chars except tab/newline/CR).
_INVALID_XML_CHARS = re.compile(
    "[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x84\x86-\x9f]"
)


def _safe_cdata(text: str) -> str:
    """
    Make AI-generated text safe to embed in a CDATA block:
    - strips characters that aren't valid in XML 1.0 at all
    - escapes any literal ']]>' sequence, which would otherwise
      prematurely terminate the CDATA section and corrupt the file
      (e.g. if the Lua code happens to contain that exact sequence)
    """
    text = _INVALID_XML_CHARS.sub("", text or "")
    return text.replace("]]>", "]]]]><![CDATA[>")

_ref_counter = itertools.count(1)

SHAPE_MAP = {"Ball": "0", "Cylinder": "2", "Block": "1"}
MATERIAL_MAP = {
    "Plastic": "256", "Wood": "512", "Metal": "1088",
    "Concrete": "816", "Grass": "1280", "Sand": "1296",
    "Neon": "288", "Glass": "1568",
}


def _ref() -> str:
    return f"RBX{next(_ref_counter)}"


def _part_xml(part: dict) -> str:
    ref = _ref()
    name = sx.escape(_INVALID_XML_CHARS.sub("", part.get("name", "Part")))
    size = part.get("size", [4, 4, 4])
    pos = part.get("position", [0, 0, 0])
    color = part.get("color", [163, 162, 165])
    shape = SHAPE_MAP.get(part.get("shape", "Block"), "1")
    material = MATERIAL_MAP.get(part.get("material", "Plastic"), "256")
    anchored = "true" if part.get("anchored", True) else "false"

    return f"""
    <Item class="Part" referent="{ref}">
      <Properties>
        <string name="Name">{name}</string>
        <token name="Shape">{shape}</token>
        <token name="Material">{material}</token>
        <Color3uint8 name="Color3uint8">{int(color[0])},{int(color[1])},{int(color[2])}</Color3uint8>
        <bool name="Anchored">{anchored}</bool>
        <Vector3 name="size">
          <X>{size[0]}</X><Y>{size[1]}</Y><Z>{size[2]}</Z>
        </Vector3>
        <CoordinateFrame name="CFrame">
          <X>{pos[0]}</X><Y>{pos[1]}</Y><Z>{pos[2]}</Z>
          <R00>1</R00><R01>0</R01><R02>0</R02>
          <R10>0</R10><R11>1</R11><R12>0</R12>
          <R20>0</R20><R21>0</R21><R22>1</R22>
        </CoordinateFrame>
      </Properties>
    </Item>"""


def _script_xml(script: dict) -> str:
    ref = _ref()
    name = sx.escape(_INVALID_XML_CHARS.sub("", script.get("name", "Script")))
    script_class = script.get("script_type", "Script")
    source = _safe_cdata(script.get("source", ""))

    return f"""
    <Item class="{script_class}" referent="{ref}">
      <Properties>
        <string name="Name">{name}</string>
        <ProtectedString name="Source"><![CDATA[{source}]]></ProtectedString>
      </Properties>
    </Item>"""


def build_place_xml(parts: list, scripts: list) -> str:
    """
    parts: list of part dicts (see ai_planner.generate_build_task)
    scripts: list of dicts with 'parent' key ('Workspace' or 'ServerScriptService')
             plus name/script_type/source (see ai_planner.generate_script_task)
    """
    workspace_items = "\n".join(_part_xml(p) for p in parts)

    server_scripts = [s for s in scripts if s.get("parent", "ServerScriptService") != "Workspace"]
    workspace_scripts = [s for s in scripts if s.get("parent") == "Workspace"]

    workspace_script_items = "\n".join(_script_xml(s) for s in workspace_scripts)
    server_script_items = "\n".join(_script_xml(s) for s in server_scripts)

    return f"""<?xml version="1.0" encoding="utf-8"?>
<roblox xmlns:xmine="http://www.roblox.com/roblox" version="4">
  <Item class="Workspace" referent="{_ref()}">
    <Properties>
      <string name="Name">Workspace</string>
    </Properties>
    {workspace_items}
    {workspace_script_items}
  </Item>
  <Item class="ServerScriptService" referent="{_ref()}">
    <Properties>
      <string name="Name">ServerScriptService</string>
    </Properties>
    {server_script_items}
  </Item>
</roblox>"""
